travis:
  secure:
    BINSTAR_TOKEN: BPNJuAP4ZiENMv0NF9gfvFfWoTHhScnTSB96QCg1BhSFuUyK+wJHbEX014uZEjNQIglO7gZTUxy1kINibeMXV5Om+IntXXxCtrpqZuyKAuYRSFuXT7sKafkbaU1M44Fc2BP5YjmY+3hfgzirdc8MSRQzPHaVtaie7NdtF7j9g/9KhsyN0Z1Syg68PPDYXlHNqSnA2c7ftqTIFapU2Zl6bgrsAia5Ov+BlCRCkaRfoN7iFbEuDmPiLZ/aDqZC1gK0VcCZ82gvXjHfmD3f0ij84fDPqg8ihpQUSRuAVPXsP/DgEwBfppehKwFaWE0JkOmvmVRQIfzk5n6gtgTdMoNPN9mC4IUz976ggkS+TEy8Eqqg+XB0sU85IHPhB/r7fMw9Xf5YTNl3CP/b1GqfW7mWt1dDZegOVZ+KL3H/V/vdTrp/LULUdRpvx41nIfq5vRbYHw+RueO8mfdM5xxNoAPa8RSeoHKhL2HAARhQg0kCxFDqhKoXFmypFNTmX4teVuFzBz6imAoeyKpZBC7umf7tSCOFsz+YZtTXCOMpM/evjBBpe5+F3Oq7iQLnjwvkQYqnZSp7WJLm9cN2yumvmv21lv+iPXVA7dS23XdrNHFLhaPF2Rpn30YG/BOHcGo39V9mfn11G2s+yOmLfkux1pWSI56fa8X7DinY7b4vXP938ME=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
